{% set name = "soxspipe" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad48aef026488975f93709dbea8ee6870a89b5a47999bb3cec9f92f67e9357c9

build:
  number: 0
  entry_points:
    - soxspipe=soxspipe.cl_utils:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - astropy
    - bottleneck
    - ccdproc
    - docopt
    - fundamentals
    - matplotlib-base
    - numpy
    - pandas
    - pathlib
    - photutils
    - python >=3.6
    - pyyaml
    - tabulate
    - unicodecsv
    - multiprocess

test:
  imports:
    - soxspipe
    - soxspipe.commonutils
    - soxspipe.recipes
  commands:
    - soxspipe --help

about:
  home: https://github.com/thespacedoctor/soxspipe
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: A python package and command-line tools to The data-reduction pipeline for the SOXS instrument
  doc_url: https://soxspipe.readthedocs.io
  dev_url: https://github.com/thespacedoctor/soxspipe

extra:
  recipe-maintainers:
    - thespacedoctor
